[package]
name = "netcanv"
version = "0.1.0"
authors = ["lqdev <liquidekgaming@gmail.com>"]
edition = "2018"

[workspace]
members = ["netcanv-matchmaker"]

[dependencies]
winit = "0.22.2"
skulpin = { version = "0.11.2", default-features = false, features = ["skia_complete", "skulpin_winit", "winit-22"] }
laminar = "0.4.0"
serde = { version = "1.0.123", features = ["derive"] }
bincode = "1.3.2"
crossbeam-channel = "0.4.4"
thiserror = "1.0.24"

