[package]
name = "netcanv"
version = "0.2.1"
authors = ["lqdev <liquidekgaming@gmail.com>"]
edition = "2018"

[workspace]
members = ["netcanv-matchmaker", "netcanv-protocol"]

[dependencies]

# Common things
anyhow = "1.0.40"

# Windowing and graphics
winit = "0.24.0"
skulpin = { version = "0.14.0", features = ["skia-complete", "winit-app", "winit-24"] }
native-dialog = "0.5.5"
image = { version = "0.23.14", default-features = false, features = ["png", "webp"] }
webp = { version = "0.2.0", features = ["img"] }
usvg = { version = "0.14.0", default-features = false }
resvg = { version = "0.14.0", default-features = false }
tiny-skia = { version = "0.5.0", default-features = false, features = ["std", "simd"] }

# Networking
serde = { version = "1.0.123", features = ["derive"] }
bincode = "1.3.2"

# Multithreading
nysa = "0.2.2"

# Utilities
directories = "3.0.2"
toml = "0.5.8"

# Clipboard
copypasta = "0.7.1"

# Workspace
netcanv-protocol = { path = "netcanv-protocol" }

[profile.release]
lto = "thin"
