[package]
name = "netcanv-matchmaker"
version = "0.1.0"
authors = ["lqdev <liquidekgaming@gmail.com>"]
edition = "2018"

[dependencies]
laminar = "0.4.0"
serde = { version = "1.0.123", features = ["derive"] }
bincode = "1.3.2"
rand = "0.8.3"

