name: Build AppImage

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-appimage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Generate AppImages
      run: cd resources ; ../contrib/generate.sh
    - name: Upload AppImages as Artifact
      uses: actions/upload-artifact@v2.2.2
      with:
        name: AppImages
        path: appimage/out/
